services:
  rydia:
    image: rydia
    build:
      context: .
      dockerfile: src/Rydia.API/Dockerfile
    ports:
      - 5144:5144
    env_file:
      - .env
    depends_on:
      - pgsql
    networks:
      - rydia

  pgsql:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-rydia}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-rydia}
      - POSTGRES_DB=${POSTGRES_DB:-rydia_db}
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rydia

volumes:
  pgsql_data:

networks:
  rydia:
    driver: bridge